# Generated by Django 4.1.5 on 2023-02-03 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0004_alter_user_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookToken', models.TextField()),
                ('facebookUserId', models.BigIntegerField()),
                ('pageId', models.BigIntegerField()),
                ('pageName', models.CharField(max_length=1000)),
                ('pageToken', models.TextField()),
                ('adAccountId', models.BigIntegerField()),
                ('adAccountName', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
