# Generated by Django 4.1.5 on 2023-02-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0005_facebookintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookintegration',
            name='adAccountId',
            field=models.CharField(max_length=200),
        ),
    ]
