# Generated by Django 4.1.5 on 2023-02-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0007_campaigndetail_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndetail',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Paused', 'Paused')], default='Active', max_length=100),
        ),
    ]
